resource_group_name  = "tfstate-rg"
storage_account_name = "mevtfstatebucket"
container_name       = "tfstate"
key                  = "dynamicepehemral-daj-base-env"
access_key           = "VAR_ACCESSKEY"
