name: 1. Create Repositories From Templates
on:
  workflow_dispatch:

jobs:
  create-repo:
    runs-on: ubuntu-latest  
    name: 'Creating new repo'
    steps:
    - name: Creating 
      run: |
         gh repo create ES-BAR-MEV/jrq-project --private --template ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-DAJ-k8s
      env:
          GH_TOKEN: "${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN  }}"

  grant-repo-permissions:
    needs: [create-repo]
    runs-on: ubuntu-latest  
    name: 'Granting permissions to repo'
    steps:
    - name: Creating 
      run: |
         gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ES-BAR-MEV/jrq-project/actions/permissions/access -f "access_level=organization"
      env:
          GH_TOKEN: "${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN  }}"
