name: 2. Configure And Create Projects
on:
  workflow_dispatch:
    inputs:
      PROJECT_CODE:
        description: 'Project Code: (Example: demo)'
        required: true
        default: ""
        type: text

jobs: 
  call-workflow-passing-data:
    name: 'Calling the external workflows to configure and create the project'
    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-${{ github.event.inputs.PROJECT_CODE }}-k8s/.github/workflows/called-workflow.yml@main
    with:
      PROJECT_CODE: ${{ github.event.inputs.PROJECT_CODE }}
