name: '2. Destroy Dynamic Ephemeral Project'

on:
  workflow_dispatch:
    inputs:
      PROJECT_CODE:
        description: 'Project Code: (Example: demo)'
        required: true
        default: ""
        type: text
      DELETE_OR_ARCHIVE:
        type: choice
        description: What do you want to do with the project repositories?
        options: 
        - archive
        - delete
      password:
        description: 'Check in shared keys PWD_GITHUB_TF_DESTROY. Only required when Dry run is NOT checked '
        required: false
        type: string
        default: pwd

jobs:
  check_password:
    runs-on: ubuntu-latest
    steps:
    - name: Verify password
      run: |
        set -e
        echo "Verifying password..."
        INPUT_PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH) >> $GITHUB_ENV
        INPUT_PASSWORD_HASH=$(echo -n "$INPUT_PASSWORD" | base64 )

        if [[ "$INPUT_PASSWORD_HASH" == "cDQ0c3RmZDNsM3Qz" ]]; then
          echo "Password verification successful."
        else
          echo "Password verification failed."
          exit 1
        fi
        
  format_prj_coode:
    needs: [ check_password ]
    outputs:
      prj_code_lower: ${{ steps.var.outputs.prj_code_lower}}
      prj_code_upper: ${{ steps.var.outputs.prj_code_upper}}
    runs-on: "ubuntu-latest"
    steps:
      - name: Setting prj code to lower
        uses: actions/github-script@v6
        id: var
        with:
          script: |
            core.setOutput('prj_code_lower', '${{github.event.inputs.PROJECT_CODE }}'.toLowerCase().replaceAll(/[/.]/g, '-').trim('-'));
            core.setOutput('prj_code_upper', '${{github.event.inputs.PROJECT_CODE }}'.toUpperCase().replaceAll(/[/.]/g, '-').trim('-'));     

  choose-delete-or-archive-project:
    needs: [ format_prj_coode ]
    name: 'Choosing delete or archive repositories'
    runs-on: ubuntu-latest
    env:
      PROJECT_CODE_LOWERCASE: ${{ needs.format_prj_coode.outputs.prj_code_lower }}
      PROJECT_CODE_UPPERCASE: ${{ needs.format_prj_coode.outputs.prj_code_upper }}
    steps:
    - name: Check out repository code for ${{ env.PROJECT_CODE_UPPERCASE }}-base
      uses: actions/checkout@v4
      with:
        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-${{ env.PROJECT_CODE_UPPERCASE }}-base
        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
    - name: Choose option on repo ${{ env.PROJECT_CODE_UPPERCASE }}-base
      run: |
        sed -i "s#DELETE_OR_ARCHIVE#${{ github.event.inputs.DELETE_OR_ARCHIVE }}#g" .github/workflows/reusable-destroy-dynamicephemeral-base.yaml
        git config --global user.name "Configure Project"
        git config --global user.email "configure.project@atos.net"
        git add -A
        git commit -m "Choosing delete or archive project"
        git push
    - name: Check out repository code for ${{ env.PROJECT_CODE_UPPERCASE }}-frontend-aks
      uses: actions/checkout@v4
      with:
        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-${{ env.PROJECT_CODE_UPPERCASE }}-frontend-aks
        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
    - name: Choose option on repo ${{ env.PROJECT_CODE_UPPERCASE }}-frontend-aks
      run: |
        sed -i "s#DELETE_OR_ARCHIVE#${{ github.event.inputs.DELETE_OR_ARCHIVE }}#g" .github/workflows/reusable-destroy-dynamicephemeral-frontend-aks-env.yaml
        git config --global user.name "Configure Project"
        git config --global user.email "configure.project@atos.net"
        git add -A
        git commit -m "Choosing delete or archive project"
        git push
    - name: Check out repository code for ${{ env.PROJECT_CODE_UPPERCASE }}-k8s
      uses: actions/checkout@v4
      with:
        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-${{ env.PROJECT_CODE_UPPERCASE }}-k8s
        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
    - name: Choose option on repo ${{ env.PROJECT_CODE_UPPERCASE }}-k8s
      run: |
        sed -i "s#DELETE_OR_ARCHIVE#${{ github.event.inputs.DELETE_OR_ARCHIVE }}#g" .github/workflows/reusable-destroy-dynamicepehemral-k8s.yaml
        git config --global user.name "Configure Project"
        git config --global user.email "configure.project@atos.net"
        git add -A
        git commit -m "Choosing delete or archive project"
        git push

  executing-destroy-workflow:
    needs: [ choose-delete-or-archive-project, format_prj_coode ]
    name: 'starting the destruction workflows'
    runs-on: ubuntu-latest
    env:
      PROJECT_CODE_LOWERCASE: ${{ needs.format_prj_coode.outputs.prj_code_lower }}
      PROJECT_CODE_UPPERCASE: ${{ needs.format_prj_coode.outputs.prj_code_upper }}
    steps:
    - name: Check out repository code for ${{ env.PROJECT_CODE_UPPERCASE }}-k8s
      uses: actions/checkout@v4
      with:
        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-${{ env.PROJECT_CODE_UPPERCASE }}-k8s
        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
    - name: Create the file run_creation_workflow.txt for ${{ env.PROJECT_CODE_UPPERCASE }}-k8s
      run: |
        echo "THIS REPO HAS BEEN CALLED FROM SHUTTLE WORKFLOW. DO NOT DELETE IT" >> DO_NOT_TOUCH/run_destroy_workflow.txt
        git config --global user.name "Configure Project"
        git config --global user.email "configure.project@atos.net"
        git add -A
        git commit -m "Confirmation of project configuration"
        git push

  removing-creation-template-file:
    needs: [ executing-destroy-workflow, format_prj_coode]
    name: 'Removing creation template file'
    runs-on: ubuntu-latest
    env:
      PROJECT_CODE_LOWERCASE: ${{ needs.format_prj_coode.outputs.prj_code_lower }}
      PROJECT_CODE_UPPERCASE: ${{ needs.format_prj_coode.outputs.prj_code_upper }}
    steps:
    - name: Check out local repository code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
    - name: Rollback params file
      run: |
         chmod 755 params/find_next_conf.sh; params/find_next_conf.sh out ${{ env.PROJECT_CODE_UPPERCASE }}
    - name: Removing file .github/workflows/${{ env.PROJECT_CODE_UPPERCASE }}_configure_and_create_project.yaml
      run: |
        rm  .github/workflows/${{ env.PROJECT_CODE_UPPERCASE }}_configure_and_create_project.yaml
        git config --global user.name "Configure Project"
        git config --global user.email "configure.project@atos.net"
        git add -A
        git commit -m "Destroying project configuration"
        git push
