name: Caller-Wrokflow

on:
  workflow_dispatch:
    inputs:
      PROJECT_CODE:
        description: 'Project Code: (Example: demo)'
        required: true
        default: ""
        type: text

jobs:
  call-workflow-passing-data:
    name: Call another WF
    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-DAJ-k8s/blob/main/.github/workflows/called-workflow.yaml@main
    with:
      PROJECT_CODE: ${{ github.event.inputs.PROJECT_CODE }}
