name: Caller-Wrokflow
on:
  workflow_dispatch:
    inputs:
      PROJECT_CODE:
        description: 'Project Code: (Example: demo)'
        required: true
        default: ""
        type: text

#jobs:
#  call-workflow-passing-data:
#    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-DAJ-k8s/.github/workflows/called-workflow.yml@main
#    with:
#      PROJECT_CODE: ${{ github.event.inputs.PROJECT_CODE }}

jobs:
  configure-project:
    runs-on: ubuntu-latest  
    name: 'New repo'
    steps:
    - name: Creating 
      run: |
         gh api --method PUT -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ES-BAR-MEV/jrq-project/actions/permissions/access -f "access_level=organization"
      env:
          GH_TOKEN: "${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN  }}"

#         gh repo create ES-BAR-MEV/jrq-project --private --template ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-DAJ-k8s


#  call-workflow-passing-data:
#    uses: ES-BAR-MEV/jrq-project/.github/workflows/called-workflow.yml@main
#    with:
#      PROJECT_CODE: ${{ github.event.inputs.PROJECT_CODE }}


#clone it
#as commented remove the .git folder
#git init .
#git add .
#git commit -m "First commit"
#create a new empty repository on GitHub using the new gh CLI: gh repo create
#git push -u origin master

