name: Caller-Wrokflow
on:
  workflow_dispatch:
    inputs:
      PROJECT_CODE:
        description: 'Project Code: (Example: demo)'
        required: true
        default: ""
        type: text

#jobs:
#  call-workflow-passing-data:
#    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-DAJ-k8s/.github/workflows/called-workflow.yml@main
#    with:
#      PROJECT_CODE: ${{ github.event.inputs.PROJECT_CODE }}

jobs:
  configure-project:
    runs-on: ubuntu-latest  
    name: 'New repo'
    steps:
    - name: Creating 
      run: |
         git clone git@github.com:ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-DAJ-k8s.git
      env:
          GH_TOKEN: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN  }}


#clone it
#as commented remove the .git folder
#git init .
#git add .
#git commit -m "First commit"
#create a new empty repository on GitHub using the new gh CLI: gh repo create
#git push -u origin master

