name: Caller-Wrokflow
on:
  workflow_dispatch:
    inputs:
      PROJECT_CODE:
        description: 'Project Code: (Example: demo)'
        required: true
        default: ""
        type: text

#jobs:
#  call-workflow-passing-data:
#    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-DAJ-k8s/.github/workflows/called-workflow.yml@main
#    with:
#      PROJECT_CODE: ${{ github.event.inputs.PROJECT_CODE }}

jobs:
  configure-project:
    runs-on: ubuntu-latest  
    name: 'New repo'
    steps:
    - name: Creating 
      run: |
         gh repo create jrq-test --template="ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-DAJ-k8s"
      env:
          GH_TOKEN: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN  }}
