name: Configure And Create Projects for VAR_TEMPLATE_PROJECT_CODE_UPPERCASE
on:
  workflow_dispatch:
    inputs:
      PROJECT_CODE:
        description: 'Project Code: (Example: demo)'
        required: true
        default: ""
        type: text

jobs: 
  call-workflow-k8s:
    name: 'Calling the external k8s workflows to configure and create the project'
    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s/.github/workflows/called-workflow.yml@main
    with:
      PROJECT_CODE: ${{ github.event.inputs.PROJECT_CODE }}
  call-workflow-frontend:
    name: 'Calling the external frontend workflows to configure and create the project'
    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-frontend-aks/.github/workflows/called-workflow.yml@main
    with:
      PROJECT_CODE: ${{ github.event.inputs.PROJECT_CODE }}
