name: Test
on:
  workflow_dispatch:

jobs:
  configure-project:
    runs-on: ubuntu-latest  
    name: 'Print'
    steps:
    - name: Search file
      run: |
         /params/find_next_conf.sh in DAJ
