name: test
on:
  workflow_dispatch:
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ES-BAR-MEV-ITSM/ITSM_INC_PROD
        ref: main
        token: ${{ secrets.DYNAMICEPHEMERAL_ISSUES_TOKEN }}
    - name: Create Issue
      run: |
        echo "Creating new issue..."
        cat Cloud_Infra_DNS_Entries_Request_to_add.md | sed -e "s/{{NAMES}}/argocd-daj, prometheus-daj/" | sed -e "s/{{LOAD_BALANCER_IP}}/172.122.33.158/" | github-issue create


