name: Test
on:
  workflow_dispatch:

jobs: 
  load-env-vars:
    name: 'Load env vars'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Load from file
      uses: cardinalby/export-env-action@v1
      with:
        envFile: 'params/01_params.env'
        expand: 'true'
      
# env.PROTOCOL == 'https'
# env.HOST == 'example.com'
# env.PORT == '8080'
# env.URI == 'https://example.com:8080'
