name: Print variables from another workflow
on:
  workflow_call:
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ES-BAR-MEV-ITSM/ITSM_INC_PROD
    - name: Create Issue
      run: |
        echo "Creating new issue..."
        cat Cloud_Infra_DNS_Entries_Request.md | sed -e "s/{{NAMES}}/argocd-daj, prometheus-daj/" | sed -e "s/{{LOAD_BALANCER_IP}}/172.122.33.158/" | github-issue create


